export const petNames = [
  "Buddy",
  "Luna",
  "Max",
  "Milo",
  "Bailey",
  "Charlie",
  "Lucy",
  "Cooper",
  "Leo",
  "Rocky",
  "Chloe",
  "Daisy",
  "Sadie",
  "Tucker",
  "Lola",
  "Oliver",
  "Coco",
  "Zoe",
  "Ruby",
  "Lily",
  "Zeus",
  "Roxy",
  "Oscar",
  "Riley",
  "Molly",
  "Bentley",
  "Sunny",
  "Winston",
  "Lulu",
  "Teddy",
  "Casper",
  "Mia",
  "Bear",
  "Sophie",
  "Jack",
  "Hazel",
  "Duke",
  "Maggie",
  "Apollo",
  "Penny",
  "Rusty",
  "Ginger",
  "Finn",
  "Nala",
  "Olive",
  "Harley",
  "Piper",
  "Murphy",
  "Gracie",
  "Simba",
];

export const petEmojis = [
  "🐶",
  "🐱",
  "🐰",
  "🦁",
  "🐻",
  "🐯",
  "🐼",
  "🐨",
  "🐮",
  "🐷",
  "🐵",
  "🐸",
  "🐙",
  "🐢",
  "🐍",
  "🦎",
  "🐬",
  "🐳",
  "🐎",
  "🦄",
  "🐔",
  "🐧",
  "🦆",
  "🦉",
  "🦅",
  "🦇",
  "🐝",
  "🦋",
  "🐞",
  "🐜",
  "🐠",
  "🐡",
  "🦑",
  "🦐",
  "🐙",
  "🐛",
  "🦕",
  "🦖",
  "🐊",
  "🐋",
  "🦈",
  "🦓",
  "🦍",
  "🦒",
  "🐘",
  "🦏",
  "🐪",
  "🐫",
  "🦙",
  "🐄",
];

export const goodbyeWord = [
  "May your spirit find its way to a place of eternal peace.",
  "Your memory will forever linger in our hearts.",
  "Though you're gone, your love will forever be a part of us.",
  "As you cross the rainbow bridge, know that you were deeply loved.",
  "Your paws left footprints on our hearts that time will never erase.",
  "In your absence, our home feels emptier, but our memories are full.",
  "You brought immeasurable joy into our lives, and your absence brings tears.",
  "Farewell, dear friend. Your presence will be sorely missed.",
  "Thank you for the years of companionship and unwavering love.",
  "As you journey beyond this world, may you find endless fields to roam.",
  "You may be gone from sight, but never from our hearts.",
  "Your loyalty and love enriched our lives in ways words cannot express.",
  "Although you've left this earthly realm, your spirit remains forever by our side.",
  "Your wagging tail and gentle purrs are now sweet memories we hold dear.",
  "The bond we shared with you will never be broken, even in your absence.",
  "Your playful spirit brought smiles that will continue to brighten our days.",
  "Saying goodbye is never easy, but your impact on our lives was profound.",
  "In your honor, we'll carry forward the love and happiness you brought us.",
  "You were more than a pet; you were family, and you'll be cherished forever.",
  "The stars above now have a new companion shining brightly.",
  "Rest in peace, dear friend. You've earned your eternal slumber.",
  "Your presence was a gift we'll forever be thankful for.",
  "Though you're no longer with us, your love leaves an indelible mark.",
  "May you find endless fields to explore and plenty of treats over the rainbow bridge.",
  "Your memory will continue to warm our hearts on even the coldest days.",
  "As we say goodbye, we remember the joy and comfort you brought us.",
  "You were a true and loyal companion, and your absence is deeply felt.",
  "The pain of parting is immense, but so is the love and happiness you gave us.",
  "In your honor, we'll cherish each day and the love you brought into our lives.",
  "Farewell, furry friend. Your memory will forever brighten our lives.",
  "Although you've left this world, you'll never leave our thoughts and hearts.",
  "You were a source of strength and solace, and your memory will sustain us.",
  "Your time with us was a gift we'll forever hold dear.",
  "May you find endless fields to run in and sunshine to bask under.",
  "Your love was unconditional, and its warmth will remain in our hearts.",
  "As you find peace in the beyond, know that you were deeply cherished.",
  "Though you're gone, your spirit will forever dance in the wind.",
  "In your absence, we find solace knowing you're no longer in pain.",
  "Your memory will be a blessing that we'll carry with us always.",
  "Saying goodbye is never easy, but we're grateful for the moments we shared.",
  "May your journey over the rainbow bridge be filled with love and serenity.",
  "Your companionship brought us joy beyond measure, and your loss brings tears.",
  "Rest in peace, dear companion. Your legacy will continue to inspire.",
  "Your presence in our lives was a precious gift we'll forever treasure.",
  "As you find eternal rest, know that you'll never truly leave us.",
  "Your memory will live on as a reminder of the love and happiness you brought.",
  "In your memory, we'll strive to be as kind and loving as you were.",
  "Though you've left this world, your spirit remains in every corner of our home.",
  "You touched our lives in ways we can't express, and for that, we're thankful.",
  "Farewell, beloved friend. The imprint you left on our hearts is eternal.",
  "Though you're no longer with us, your love continues to guide us.",
  "May you find endless fields to explore, with treats aplenty on your journey.",
  "Your time with us was a blessing, and your memory is a treasure we'll keep.",
];
